pmndrs/cannon-es

src/math/Vec3.js, src/shapes/Box.js, src/shapes/ConvexPolyhedron.js, src/shapes/Sphere.js
Additionally adds an extra parameter to bypass bounding sphere radius and faceNormals calculations, if supplied with a THREE.Geometry that contains such information.
These changes work in tandem with changes in use-cannon, to better support ConvexPolyHedron.
--
While looking into this I cleaned up some formatting, passed axes to the convexPoly constructor within Box, and corrected the sphere volume formula.
=> Prevent inopportune collision errors with unconnected faces in Convex shapes 

src/shapes/Box.js, src/shapes/ConvexPolyhedron.js
How do we feel about passing vertices, faces, normals and other information to the ConvexPolyhedron constructor as an object?
```js
constructor({ vertices = [], faces = [], normals = [], axes, boundingSphereRadius }) {
```
I feel as if it makes passing available data, especially with gaps in it, a little easier.
=> Proposal: pass object to convexPolyhedron

readme.md, src/collision/Broadphase.ts, src/collision/Ray.ts, src/constraints/DistanceConstraint.ts, src/material/ContactMaterial.ts, src/math/Quaternion.ts, src/math/Vec3.ts, src/objects/Body.ts, src/objects/RaycastVehicle.ts, src/objects/RigidVehicle.ts, src/objects/SPHSystem.ts, src/objects/Spring.ts, src/shapes/Box.ts, src/shapes/ConvexPolyhedron.ts, src/shapes/Heightfield.ts, src/shapes/Shape.ts, src/shapes/Trimesh.ts, src/world/Narrowphase.ts, src/world/World.ts
* Remove deprecated World methods (`World.add`, `World.remove`)
* Use `World.addBody` and `World.removeBody` instead
* Remove deprecated Vec3 methods (norm, norm2, mult)
* Use `Vec3.length`, `Vec3.lengthSquared`, and `Vec3.scale` instead
* Restore JSDoc @todo and @deprecated comments from TS refactor
* Restore uninitialized class properties
* Remove "Class.prototype.constructor = Class" assignments
=> Address some readme todo tasks

dist/cannon-es.cjs.js, package.json, rollup.config.js, yarn.lock
Close #23
`@babel/runtime` wasn't in the dependencies so it was throwing an error in non-babel environments.
See doc here:
https://babeljs.io/docs/en/babel-plugin-transform-runtime
However, we don't really need `@babel/plugin-transform-runtime` as it ends up saving only ~100 bytes.
With `@babel/plugin-transform-runtime`:
Without `@babel/plugin-transform-runtime`:
So I removed it along other unused babel plugins.
=> Fix babel error

dist/cannon-es.cjs.js, dist/cannon-es.js, package.json, src/shapes/Cylinder.ts, yarn.lock
=> Fix cylinder axis orientation, update deps, bump version to 0.10.0

dist/cannon-es.cjs.js, dist/cannon-es.js, package.json, rollup.config.js, src/world/World.ts, yarn.lock
Close #37 
I've found a solution which reconciles the usage in the browser, webpack and node environments. Let me explain it:
By default we use `window.performance` in the source code. This gets bundled as a module into `dist/cannon-es.js`. This works fine in browser environments and in webpack, since webpack uses the bundle in the `module` field of the package.json.
In the commonjs bundle instead, which is supposed to be used in node environments only (I imagine browserify), we replace `window.performance` with `require('perf_hooks').performance`.
In this PR, I also removed unnecessary rollup config and updated the rollup devDependencies.
=> Use perf_hooks only in the commonjs bundle

dist/cannon-es.cjs.js, dist/cannon-es.js, rollup.config.js, src/world/World.ts
Using window in a worker throws an error, let's use [`globalThis`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis) instead.
Its browser support seems aligned with our browser support specified [here](https://github.com/react-spring/cannon-es/blob/fc0f1c481d09db667f170acafb8651d03bd37bb8/rollup.config.js#L20).
- `globalThis` browser support: https://caniuse.com/#feat=mdn-javascript_builtins_globalthis
- our supported browsers: https://browsersl.ist/?q=%3E1%25%2C+not+dead%2C+not+ie+11%2C+not+op_mini+all
Instead, if there is the need to support older browsers, we can easily transpile `globalThis` with babel.
=> Fix issue with window in worker

dist/cannon-es.cjs.js, dist/cannon-es.d.ts, dist/cannon-es.js, examples/convex.html, examples/shapes.html, examples/stacks.html, readme.md, src/collision/Ray.ts, src/shapes/Cylinder.ts, src/shapes/Shape.ts, src/world/Narrowphase.ts
Original issue: https://github.com/schteppe/cannon.js/issues/329
Since the cylinder is a ConvexPolyhedron under the hood, it was using its type to test the collisions agains other objects.
Now that it has a type by itself, the Cylinder collisions methods were needed. I created them and made them call the ConvexPolyhedron collisions methods.
I also exposed the `radiusTop` `radiusBottom` `height` `numSegments` properties of the Cylinder.
=> Set Cylynder.type correctly when creating a Cylinder

src/world/World.ts
After doing some tests, it made more sense to keep the threshold at which we skip to the next internalStep at 60fps, since it dips anyway to much lower than 60fps sometimes.
It was originally like this:
https://github.com/schteppe/cannon.js/blob/2cd242e696cd37b67a5722000abaf3edeef1d29a/src/world/World.js#L506-L509
=> Performance: move the bailout threshold to 60fps instead of 30fps

examples/impulses.html, examples/sleep.html, readme.md, src/objects/Body.ts
Related to #56
Also in other engines, if a force is applied to a sleeping body, it wakes up.
I also fixed the JSDoc comments and made the second parameter of `applyForce` and `applyImpulse` optional.
=> Wakeup a body if a force is applied to it

src/collision/ArrayCollisionMatrix.ts, src/collision/Broadphase.ts, src/collision/ObjectCollisionMatrix.ts, src/math/Vec3.ts, src/shapes/Box.ts, src/shapes/ConvexPolyhedron.ts, src/shapes/Trimesh.ts, src/utils/Utils.ts
For the already static methods, let's convert them fully to static methods since there is no performance difference between the two modes, I've tested this. Under the hood, class use prototypal inheritance, so memory-wise, is the same thing.
This PR contains some stuff from #47, however I didn't convert the non-static methods to static methods since there is no need to, and most likely doesn't end up in any memory savings.
https://stackoverflow.com/questions/34898166/javascript-class-static-methods-memory-consumption
=> Use the static keyword for static methods

src/solver/SplitSolver.ts
Close #57 
The SplitSolver is used like this
```js
const subsolver = new CANNON.GSSolver()
subsolver.iterations = 50
subsolver.tolerance = 0.0001
world.solver = new CANNON.SplitSolver(subsolver)
```
So it makes sense for its type to be a GSSolver.
=> Set SplitSolver parameter type as GSSolver

src/objects/WheelInfo.ts
As discussed in #65, align the `WheelInfo.frictionSlip` default value to the [bullet default value](https://github.com/bulletphysics/bullet3/blob/afa4fb54505fd071103b8e2e8793c38fd40f6fb6/src/BulletDynamics/Vehicle/btRaycastVehicle.h#L45).
=> Make WheelInfo.frictionSlip default to a lower value

src/math/Mat3.test.ts, src/math/Mat3.ts, src/math/Quaternion.test.ts, src/math/Vec3.test.ts, src/math/Vec3.ts
#49 I ported over some tests from the original cannon repository and added some more to try to give each method their own test and increase code coverage. 
While writing the tests, a few things came up:
1. Mat3.getTrace was returning void, but the doc said it should return Vec3. I made the function match the doc in commit 92083c5
2. A lot of methods allowed optional "target" objects to store the response in. Most methods did this by creating an argument with a default value of an empty object. Some functions seemed to recreate that using overloaded function definitions. I didn't think that was intentional so I made default value of empty objects consistent in commit 83050fa. 
3. Mat3.mmult and Mat3.transpose were failing the tests. If you try to multiply or transpose a matrix with itself …
=> Add Mat3, Vec3, and some Quaternion tests

src/collision/AABB.test.ts
Ported the original AABB test cases into typescript, and added one more case to the `AABB.extend` test. I did not add tests for the new AABB.overlapsRay function because I don't know the expected behavior.
=> Port AABB tests

src/math/Mat3.ts
For my project I was calling Mat3.reverse about 1000 times per frame and got a load on the garbage collection. Tracking it down I found the dynamic allocation of the eqns array in the Mat3.reverse during every call, so I replaced it with a static array which should solve the issue.
=> Change Mat3.reverse to use static array

src/world/World.ts
As explained in #81, the time variable is increased two times when stepping the world. This is a bug that exists in cannon.js since the start.
The .time property is used internally only for the sleep mechanic, which makes the sleeping twice as faster.
Since `Body.sleepTimeLimit` is set to 1 second by default, this PR makes the sleeping behave correctly.
https://github.com/pmndrs/cannon-es/blob/cebdad108d0d97ff9b67cb65562ed784821f13ea/src/objects/Body.ts#L194
This is the `sleep.html` example:
| Before this PR | After this PR |
|--------|-------|
| ![image](https://user-images.githubusercontent.com/7217420/110206346-61196c80-7e7d-11eb-99bf-7ae90b4d2e10.png) |  ![image](https://user-images.githubusercontent.com/7217420/110206353-6c6c9800-7e7d-11eb-9300-f567356b0000.png) |
=> Fix redundant increment of world.time

examples/js/PointerLockControlsCannon.js, examples/threejs.html, examples/threejs_cloth.html, examples/threejs_fps.html, examples/threejs_mousepick.html, examples/threejs_voxel_fps.html, examples/worker.html, examples/worker_sharedarraybuffer.html
As illustrated in the new Getting started guide, we should make the framerate independent stepping the default method of stepping illustrated.
=> Use framerate independent stepping in examples

.eslintignore, .eslintrc.json, .gitignore, .husky/pre-commit, package.json, yarn.lock
Add eslint to improve code quality and more.
The first commit simply adds eslint, didn't wanna put more work into this before I get an OK that you think it's a good idea. The eslint conf is mostly copied directly from `use-cannon`
TODO
=> chore: add eslint

package.json, rollup.config.js
Close #89
It was messing up with the JSDoc comments.
We probably don't need babel anymore, now that create-react-app v5 is out.
=> Remove @babel/plugin-proposal-class-properties

rollup.config.js
Fixes #86
In SparkAR:
- no `window` available
- no `globalThis` available
- no `require('perf_hooks')` available
This makes performance.now() default to Date.now() in SparkAR case
=> Fix SparkAR usage

examples/threejs.html, examples/threejs_cloth.html, examples/threejs_mousepick.html, examples/worker.html, examples/worker_sharedarraybuffer.html, getting-started.md, src/world/World.ts
Closes #126
We can simplify the world stepping for the user quite a bit by keeping track of `lastCallTime` internally:
```diff
-  const timeStep = 1 / 60
-  const time = performance.now() / 1000
-  if (!lastCallTime) {
-    world.step(timeStep)
-  } else {
-    const dt = time - lastCallTime
-    world.step(timeStep, dt)
-  }
-  lastCallTime = time
+  world.fixedStep()
```
This PR adds a new method for the world, `fixedStep()`. Look at the getting started guide for updated documentation.
=> Add `world.fixedStep()`

examples/callbacks.html, src/objects/Body.ts, src/world/World.ts
See https://github.com/pmndrs/cannon-es/pull/116#issuecomment-1001694525
Removing some deprecated methods.
Use `world.addEventListener('preStep', () => {})` and `world.addEventListener('postStep', () => {})` instead.
=> Remove deprecated `body.preStep` and `body.postStep`

src/world/World.ts
See https://github.com/pmndrs/cannon-es/pull/116#issuecomment-1001694525
Removing deprecated methods, `world.addMaterial` was the predecessor of `world.addContactMaterial`.
=> Remove `world.addMaterial`

src/utils/TupleDictionary.ts, src/world/World.test.ts, src/world/World.ts
- Name matches the convention, such as `removeContraint`
- Name matches [JavaScript built-in`Map` object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/delete) which has similar methods & use case
=> Add `world.removeContactMaterial` method

src/math/Quaternion.ts
Thank you for your work maintaining this stellar project.
`Quaternion::setFromEuler` is used in the "Getting Started" example and others, but does not appear in the documentation. This PR adds a description to make typedoc include the method in the generate docs. Please let me know if you'd like me to include the generated docs in the PR.
=> Quaternion::setFromEuler documentation for TypeDoc coverage

getting-started.md
- chore(docs): add supported shape collision pairs table to getting-started.md
- taken from README.markdown in the original repository: https://raw.githubusercontent.com/schteppe/cannon.js/master/README.markdown
=> chore(docs): add supported shape collision pairs table to getting-started.md
